name: mobsfscan sarif
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
    mobsfscan:
        runs-on: ubuntu-latest
        name: run mobsf with cypress
        steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Install dependencies
          run: npm install
        - name: install and run mobsf
          run: |
            docker pull opensecurity/mobile-security-framework-mobsf:latest
            docker run -d -p 8000:8000 opensecurity/mobile-security-framework-mobsf
            sleep 60 
        - name : run cypress
          run: |
            npx cypress run
        - name: Upload MobSF report
          uses: actions/upload-artifact@v2
          with:
            name: mobsf-report
            path: ./report/pdf/report.pdf
            
