name: mobsfscan sarif
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
    mobsfscan:
        runs-on: ubuntu-latest
        name: run mobsf with cypress
        steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        - name: install mobsf
          run: |
            docker --version
            docker pull opensecurity/mobile-security-framework-mobsf:latest
